version: "2"
services:
  app:
    build: .
    links:
      - db
    ports:
      - "5001:5001"

  db:
    image: mysql:8.0
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    #   MYSQL_USER: 
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: hackathon
